# Generated by Django 3.2.4 on 2021-06-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('langue', models.CharField(choices=[('francais', 'francais'), ('anglais', 'anglais')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('datenaissance', models.DateField()),
                ('langue', models.CharField(choices=[('francais', 'francais'), ('anglais', 'anglais')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rendezvous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeExamin', models.CharField(max_length=50)),
                ('Notes', models.TextField(max_length=50)),
                ('Lieu', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('NomDocteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.docteur')),
                ('NomPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
