# Generated by Django 3.2.4 on 2021-06-06 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.EmailField(default='belx22@gmail.com', max_length=254)),
                ('nomexpediteur', models.CharField(default='abdoul', max_length=50)),
                ('destinataire', models.EmailField(default='bellofidele@gmail.com', max_length=254)),
                ('subject', models.CharField(default='rien', max_length=200)),
                ('contenu', models.TextField(blank=True, default='salutation')),
                ('dateEnvoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('atachement', models.FileField(default='img.jpg', upload_to='')),
                ('lus', models.CharField(default='non', max_length=10)),
            ],
        ),
    ]
