# Generated by Django 3.1.3 on 2021-06-09 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_medicale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principale', models.CharField(default='', max_length=50)),
                ('secondaire', models.CharField(default='', max_length=50)),
                ('hopital', models.CharField(default='', max_length=200)),
                ('observation', models.TextField(blank=True, default='RAS')),
                ('periode', models.DateTimeField(default=django.utils.timezone.now)),
                ('NomPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
