# Generated by Django 3.1.3 on 2021-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_info_medicale'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='nationalite',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='docteur',
            name='photo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
