# Generated by Django 3.1.3 on 2021-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210609_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='genre',
            field=models.CharField(choices=[('feminin', 'feminin'), ('masculin', 'masculin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('feminin', 'feminin'), ('masculin', 'masculin')], max_length=50),
        ),
    ]
