# Generated by Django 3.1.3 on 2021-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210609_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Medication',
            field=models.CharField(choices=[('paracetamol', 'Paracetamol'), ('Nivakine', 'Nivakine'), ('Amodiakine', 'Amodiakine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='TypeRapport',
            field=models.CharField(choices=[('rapport activite', 'rapport activite'), ('rapport sur les maladies', 'rapport sur les maladies')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='TypeExamin',
            field=models.CharField(choices=[('Abdominal radiology', 'Abdominal radiology'), ('Breast imaging', 'Breast imaging'), ('Cardiothoracic radiology', 'Cardiothoracic radiology'), ('Cardiovascular radiology', 'Cardiovascular radiology')], max_length=50),
        ),
    ]
