# Generated by Django 3.1.3 on 2021-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210609_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='hopital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomHopital', models.CharField(default='', max_length=50)),
                ('tel', models.CharField(default='', max_length=50)),
                ('Bp', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
