# Generated by Django 3.1.3 on 2021-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_hopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='Lieu',
            field=models.CharField(default='clinic', max_length=50),
        ),
    ]
