# Generated by Django 3.1.3 on 2021-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210610_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
    ]
