# Generated by Django 3.1.3 on 2021-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210610_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='langue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='info_medicale',
            name='periode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='langue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
