# Generated by Django 3.1.3 on 2021-06-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210610_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='specialisation',
            field=models.CharField(default='radiology', max_length=50),
        ),
    ]
