# Generated by Django 3.1.3 on 2021-06-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210611_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='profil_sante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.IntegerField(default=10)),
                ('heart', models.IntegerField(default=10)),
                ('glucose', models.IntegerField(default=10)),
                ('cholesterol', models.IntegerField(default=10)),
                ('NomPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
