# Generated by Django 3.1.3 on 2021-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_profil_sante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil_sante',
            name='blood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil_sante',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil_sante',
            name='glucose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil_sante',
            name='heart',
            field=models.IntegerField(default=0),
        ),
    ]
